server.port=${PORT:8080}
spring.application.name=collector-service

# Cloud MongoDB
spring.data.mongodb.primary.uri=mongodb+srv://ssanidhya0407:abcd%401234@api-dashboard.agbmlv0.mongodb.net/logs_db?appName=api-dashboard
spring.data.mongodb.secondary.uri=mongodb+srv://ssanidhya0407:abcd%401234@api-dashboard.agbmlv0.mongodb.net/metadata_db?appName=api-dashboard

# Local (Fallback)
# spring.data.mongodb.primary.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/logs_db}
# spring.data.mongodb.secondary.uri=${SPRING_DATA_MONGODB_SECONDARY_URI:mongodb://localhost:27017/metadata_db}

monitoring.rateLimit.override.collection=rate_limit_overrides
